FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 5173

# --host expõe o servidor do Vite para fora do container
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
